## Determinan


**Definisi:**
Determinan matriks merupakan selisih antara perkalian elemen-elemen pada diagonal utama dengan perkalian elemen-elemen pada diagonal sekunder
  
**Sifat-sifat**  
1.Determinan dari matrix indentitas adalah 1  
2.Menukar baris dan kolom pada matriks akan merubah tanda determinan  
3.jika melakukan operasi baris elementer tidak akan merubah nilai determinan  
4.Determinan a tranpose sama dengan determinan a   


In [9]:
import numpy as np

a = np.array([[1,0],[0,1]])
print(round(np.linalg.det(a)))

1


In [12]:
import numpy as np

# Definisikan matriks awal
matriks_awal = np.array([[1, 2],
                         [3, 4]])

# Hitung determinan matriks awal
det_awal = np.linalg.det(matriks_awal)
print("Determinan matriks awal:", round(det_awal))

# Menukar baris pertama dengan baris kedua
matriks_menukar_baris = matriks_awal[[1, 0]]

# Hitung determinan setelah menukar baris
det_menukar_baris = np.linalg.det(matriks_menukar_baris)
print("Determinan setelah menukar baris:", round(det_menukar_baris))

# Menukar kolom pertama dengan kolom kedua
matriks_menukar_kolom = matriks_awal[:, [1, 0]]

# Hitung determinan setelah menukar kolom
det_menukar_kolom = np.linalg.det(matriks_menukar_kolom)
print("Determinan setelah menukar kolom:", round(det_menukar_kolom))


Determinan matriks awal: -2
Determinan setelah menukar baris: 2
Determinan setelah menukar kolom: 2


In [19]:
import numpy as np

def determinant(matrix):
  """Menghitung determinan matriks persegi."""
  return np.linalg.det(matrix)

def transpose(matrix):
  """Menghitung transpose matriks."""
  return matrix.T

# Contoh matriks
matrix = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
])

# Hitung determinan dan transpose
original_determinant = determinant(matrix)
transpose_determinant = determinant(transpose(matrix))

# Tampilkan hasil
print(f"Determinan A: {original_determinant}")
print(f"Determinan A^T: {transpose_determinant}")

# Buktikan bahwa determinan sama
if original_determinant == transpose_determinant:
  print("Determinan A sama dengan determinan A^T")
else:
  print("Determinan A tidak sama dengan determinan A^T")


Determinan A: 0.0
Determinan A^T: 0.0
Determinan A sama dengan determinan A^T


In [20]:
import numpy as np

def determinant(matrix):
  """Menghitung determinan matriks persegi."""
  return np.linalg.det(matrix)

def swap_rows(matrix, i, j):
  """Menukar baris i dan j pada matriks."""
  temp = matrix[i, :]
  matrix[i, :] = matrix[j, :]
  matrix[j, :] = temp
  return matrix

def multiply_row(matrix, i, scalar):
  """Mengalikan baris i pada matriks dengan skalar."""
  matrix[i, :] *= scalar
  return matrix

def add_row_multiple(matrix, i, j, scalar):
  """Menambahkan kelipatan baris j ke baris i pada matriks."""
  matrix[i, :] += scalar * matrix[j, :]
  return matrix

# Contoh matriks
matrix = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
])

# Hitung determinan awal
original_determinant = determinant(matrix.copy())

# Tukar baris 1 dan 2
matrix = swap_rows(matrix.copy(), 0, 1)
new_determinant = determinant(matrix)
print(f"Determinan setelah menukar baris: {new_determinant}")

# Kalikan baris 2 dengan 2
matrix = multiply_row(matrix.copy(), 1, 2)
new_determinant = determinant(matrix)
print(f"Determinan setelah mengalikan baris dengan skalar: {new_determinant}")

# Tambahkan baris 2 ke baris 1
matrix = add_row_multiple(matrix.copy(), 0, 1, 1)
new_determinant = determinant(matrix)
print(f"Determinan setelah menambahkan kelipatan baris: {new_determinant}")

Determinan setelah menukar baris: 0.0
Determinan setelah mengalikan baris dengan skalar: 0.0
Determinan setelah menambahkan kelipatan baris: 0.0


**Ekspansi Kofaktor**  
Ekspansi Kofaktor adalah salah satu metode mencari determinan suatu matriks, di mana dalam metode ini memanfaatkan kofaktor.

kita akan mencari kofaktor 4x4 berikut:  

In [2]:
import numpy as np
a = np.array([[1,2,3,4],[3,2,1,3],[2,3,1,3],[3,2,3,4]])
detA = np.linalg.det(a)
print(a)
print(round(detA))

[[1 2 3 4]
 [3 2 1 3]
 [2 3 1 3]
 [3 2 3 4]]
-10


kita buktikan  


$
	\begin{bmatrix} 
	1 & 2 & 3 & 4\\ 
	3 & 2 & 1 & 3\\
  2 & 3 & 1 & 3\\
  3 & 2 & 3 & 4\\
	\end{bmatrix}
  \\
$
mengambil baris 1


$$
1 \begin{bmatrix}
2 & 1 & 3 \\
3 & 1 & 3 \\
2 & 3 & 4
\end{bmatrix}
- 2 \begin{bmatrix}
3 & 1 & 3 \\
2 & 1 & 3 \\
3 & 3 & 4
\end{bmatrix}
+ 3 \begin{bmatrix}
3 & 2 & 3 \\
2 & 3 & 3 \\
3 & 2 & 4
\end{bmatrix}
- 4 \begin{bmatrix}
3 & 2 & 1 \\
2 & 3 & 1 \\
3 & 2 & 3
\end{bmatrix}
\
$$


matriks 3x3 pertama 
$$
\begin{bmatrix}
2 & 1 & 3 \\
3 & 1 & 3 \\
2 & 3 & 4
\end{bmatrix}
\\
$$
mengambil baris 1 


$$
2 \begin{bmatrix}
1 & 3 \\
3 & 4
\end{bmatrix}
- 1 \begin{bmatrix}
3 & 3 \\
2 & 4 
\end{bmatrix}
+ 3 \begin{bmatrix}
3 & 1 \\
2 & 3
\end{bmatrix}
$$

= 2(4-9) -1 (12-6) 3 (9-2)  
= 8 - 18 - 12 + 6 + 27 - 6  
= 5  
  
matriks 3x3 kedua 

$$
\begin{bmatrix}
3 & 1 & 3 \\
2 & 1 & 3 \\
3 & 3 & 4
\end{bmatrix}
\\
$$
mengambil baris 1   


$$
3 \begin{bmatrix}
1 & 3 \\
3 & 4
\end{bmatrix}
- 1 \begin{bmatrix}
2 & 3 \\
3 & 4
\end{bmatrix}
+ 3 \begin{bmatrix}
2 & 1 \\
3 & 3
\end{bmatrix}
$$
  
  
=3(4-9)-1(8-9)3(5-3)  
=12-27-8+9+15-9  
=-5  
  
matriks 3x3 ketiga 

$$
\begin{bmatrix}
3 & 2 & 3 \\
2 & 3 & 3 \\
3 & 2 & 4
\end{bmatrix}
\\
$$
 
mengambil baris 1 

$$
3 \begin{bmatrix}
3 & 3 \\
2 & 4
\end{bmatrix}
- 2 \begin{bmatrix}
2 & 3 \\
3 & 4
\end{bmatrix}
+ 3 \begin{bmatrix}
2 & 3 \\
3 & 2
\end{bmatrix}
$$
  
=3(12-6)-2(8-9)3(4-9)  
=36-18-16+18+12-27  
= 5  
  
matriks 3x3 ke empat  
$$
\begin{bmatrix}
3 & 2 & 1 \\
2 & 3 & 1 \\
3 & 2 & 3
\end{bmatrix}
\\
$$

mengambil baris 1 

$$
3 \begin{bmatrix}
3 & 1 \\
2 & 3
\end{bmatrix}
- 2 \begin{bmatrix}
2 & 1 \\
3 & 3
\end{bmatrix}
+ 1 \begin{bmatrix}
2 & 3 \\
3 & 2
\end{bmatrix}
\\
$$

= 3(9-2)-2(6-3)1(4-9)  
= 27-6-12+6+4-9  
= 10  
  
setelah di temukan semua determinan 3x3nya kita masukan ke matriks yang tadi  

$$
1 \begin{bmatrix}
2 & 1 & 3 \\
3 & 1 & 2 \\
2 & 3 & 4
\end{bmatrix}
- 2 \begin{bmatrix}
3 & 1 & 3 \\
2 & 1 & 3 \\
3 & 3 & 4
\end{bmatrix}
+ 3 \begin{bmatrix}
3 & 2 & 3 \\
2 & 3 & 3 \\
3 & 2 & 4
\end{bmatrix} 
-4 \begin{bmatrix}
3 & 2 & 1 \\
2 & 3 & 1 \\
3 & 2 & 3
\end{bmatrix}
\\
$$
  
= 1(5)-2(-5)3(5)-4(10)  
= 5+10+15-40  
= -10  
