# Alikasi aljabar linier

Web dapat direpresentasikan seperti grafik berarah di mana node mewakili halaman web dan tepinya membentuk hubungan di antara keduanya.Biasanya, jika sebuah node (halaman web)i terhubung ke sebuah nodeJ, itu artinya i mengacu pada J.


**Page Rank**  
PageRank adalah algoritma yang Tujuan dari algoritme ini adalah untuk membantu mengidentifikasi situs web mana yang lebih penting dan oleh karena itu harus mendapat peringkat lebih tinggi pada halaman hasil mesin pencari.


**konsep power method**  
1. **Pendekatan Awal**:
   - Algoritma dimulai dengan menggunakan suatu vektor awal sebagai pendekatan awal untuk vektor eigen yang sesuai dengan nilai eigen dominan dari matriks.

2. **Iterasi**:
   - Proses iteratif dilakukan dengan mengalikan matriks yang diberikan dengan vektor pendekatan awal. Setiap iterasi meningkatkan ketepatan pendekatan terhadap vektor eigen dominan.

3. **Normalisasi**:
   - Setiap hasil perkalian matriks dan vektor dinormalisasi untuk memastikan panjang vektor tetap 1. Hal ini memungkinkan algoritma untuk konvergen menuju vektor eigen dominan.

4. **Konvergensi**:
   - Algoritma berhenti iterasi ketika perubahan antara vektor sekarang dan sebelumnya sudah cukup kecil, menandakan bahwa pendekatan vektor eigen dominan sudah cukup akurat.

5. **Perhitungan Nilai Eigen**:
   - Setelah konvergensi, nilai eigen dominan dihitung menggunakan kuotien Rayleigh, yang merupakan hasil dari perkalian vektor eigen dominan dengan matriks dan kemudian dikali lagi dengan vektor eigen dominan itu sendiri.

6. **Hasil Akhir**:
   - Hasil akhir dari algoritma adalah vektor eigen yang sesuai dengan nilai eigen dominan dari matriks yang diberikan.

In [1]:
import numpy as np

def power_method(A, b, coverage=0.05):
    b = b / np.linalg.norm(b)  # Normalize the initial vector
    previous_b = np.zeros_like(b)
    iteration = 0  # Add iteration counter
    while np.linalg.norm(b - previous_b) > coverage:
        previous_b = b.copy()  # Store a copy of the current vector
        b = np.dot(A, b)  # Apply the matrix to the vector
        norm = np.linalg.norm(b)  # Compute the norm of the vector
        b = b / norm  # Normalize the vector

        # Print the difference norm at each iteration
        difference_norm = np.linalg.norm(b - previous_b)
        print(f"Iteration {iteration}: difference norm = {difference_norm}")
        iteration += 1  # Increment iteration counter

    eigenvalue = np.dot(b.T, np.dot(A, b))  # Rayleigh quotient for the dominant eigenvalue
    return b

# Example usage
A = np.array([
    [0, 0, 0, 0, 1/3],
    [0, 0, 1/2, 1, 1/3],
    [1/3, 0, 0, 0, 1/3],
    [1/3, 0, 1/2, 0, 0],
    [1/3, 1, 0, 0, 0]
])  # Example matrix

b = np.array([0.2, 0.2, 0.2, 0.2, 0.2])  # Initial vector

eigenvector = power_method(A, b)

print("Corresponding Eigenvector:", eigenvector)

Iteration 0: difference norm = 0.480308782077982
Iteration 1: difference norm = 0.2939161841620135
Iteration 2: difference norm = 0.15699782981222282
Iteration 3: difference norm = 0.10461027073999182
Iteration 4: difference norm = 0.0650131150015595
Iteration 5: difference norm = 0.054337568885051514
Iteration 6: difference norm = 0.029126241022143836
Corresponding Eigenvector: [0.23160671 0.5927276  0.30366932 0.21574925 0.67547726]


In [2]:
def bubbleSort(eigenvector,rank):
    print('Data yang akan diurutkan:', eigenvector)
    hitung = 0
    n = len(eigenvector)
    swap = True
    while swap:
        swap = False
        hitung += 1
        print('Iterasi ke-', hitung, ':')
        for i in range(n - 1):
            if eigenvector[i] > eigenvector[i + 1]:
                rank[i],rank[i+1] = rank[i+1] ,rank [i]
                eigenvector[i], eigenvector[i + 1] = eigenvector[i + 1], eigenvector[i]
                swap = True
        n -= 1
        print(eigenvector)
    print('')
    print('Data urut:', eigenvector)
    print(rank)


rank = [0,1,2,3,4]
a = eigenvector
bubbleSort(a,rank)

Data yang akan diurutkan: [0.23160671 0.5927276  0.30366932 0.21574925 0.67547726]
Iterasi ke- 1 :
[0.23160671 0.30366932 0.21574925 0.5927276  0.67547726]
Iterasi ke- 2 :
[0.23160671 0.21574925 0.30366932 0.5927276  0.67547726]
Iterasi ke- 3 :
[0.21574925 0.23160671 0.30366932 0.5927276  0.67547726]
Iterasi ke- 4 :
[0.21574925 0.23160671 0.30366932 0.5927276  0.67547726]

Data urut: [0.21574925 0.23160671 0.30366932 0.5927276  0.67547726]
[3, 0, 2, 1, 4]
