# Program eliminasi gauss jordan menggunakan python

persamaan yang akan di eliminasi  
  
2x1 + 3x2 + 2x3 + x4 = 18  
x1 + 2x2 + 4x3 - 3x4 = 29  
3x1 + 4x2 + 2x3 + 1x4 = 21  
0x1 + 2x2 + 3x3 + 2x4 = 21

In [8]:
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

M = np.array([[2, 3, 2, 1], [1, 2, 4, 3], [3, 4, 2, 1], [0, 2, 3, 2]])
A = np.array([[2,3,2,1,1,0,0,0], [1,2,4,3,0,1,0,0], [3,4,2,1,0,0,1,0], [0,2,3,2,0,0,0,1]])

In [19]:
print(A)

[[2 3 2 1 1 0 0 0]
 [1 2 4 3 0 1 0 0]
 [3 4 2 1 0 0 1 0]
 [0 2 3 2 0 0 0 1]]


In [18]:
m1 = RowAdd(A,1,0,-1)
m2 = RowAdd(m1,0,1,-1)
m3 = RowAdd(m2,0,2,-3)
m4 = RowAdd(m3,1,2,-1)
m5 = RowAdd(m4,1,3,-2)
m6 = RowScale(m5,2,1/2)
m7 = RowAdd(m6,2,3,9)
m8 = RowAdd(m7,1,0,-1)
m9 = RowAdd(m8,2,1,-6)
m10 = RowAdd(m9,2,0,8)
m11 = RowAdd(m10,3,2,-1)
m12 = RowAdd(m11,3,1,1)
m13 = RowAdd(m12,3,0,-1)
print(m13)
invers = np.array([[1,0.5,-0.5,-1],[-2,-0.5,1.5,1],[6,0,-4,-1],[-7,0.5,4.5,1]])
hasil = np.array([[18],[29],[21],[21]])
print("")
print(invers@M)
print(invers@hasil)

[[ 1.   0.   0.   0.   1.   0.5 -0.5 -1. ]
 [ 0.   1.   0.   0.  -2.  -0.5  1.5  1. ]
 [ 0.   0.   1.   0.   6.   0.  -4.  -1. ]
 [ 0.   0.   0.   1.  -7.   0.5  4.5  1. ]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1.]
 [2.]
 [3.]
 [4.]]
